//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhạmQuangNhất_2210900115_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG_CHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG_CHIEU()
        {
            this.SUAT_CHIEU = new HashSet<SUAT_CHIEU>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public int SoGhe { get; set; }
        public string LoaiPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUAT_CHIEU> SUAT_CHIEU { get; set; }
    }
}
