//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhạmQuangNhất_2210900115_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public int MaVe { get; set; }
        public int MaSuatChieu { get; set; }
        public int MaKhachHang { get; set; }
        public int SoGhe { get; set; }
        public decimal GiaVe { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SUAT_CHIEU SUAT_CHIEU { get; set; }
    }
}
